# Generated by Django 4.2.16 on 2024-12-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_ttodo_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttodo',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
