# Generated by Django 4.2.16 on 2024-11-27 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtodoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ttodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='boards.ttodo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ttodo')},
            },
        ),
    ]
