# Generated by Django 4.2.16 on 2025-01-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jwt_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
